# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - control_statement
  - vertical_whitespace
  - trailing_whitespace
  - unused_optional_binding
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`
  - empty_string
  - multiline_parameters
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/AXPhotoViewer
analyzer_rules:
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# they can set both implicitly with an array
type_body_length:
  - 350 # warning
  - 500 # error
# implicitly
line_length:
  warning: 200
  error: 300
  ignore_function_declaration: true
  ignore_comments: true
# or they can set both explicitly
file_length:
  warning: 1000
  error: 1500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    warning: 1
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
function_parameter_count: 10
reporter: "xcode"
